# GitHub Actions workflow
# https://help.github.com/actions

name: Push (main)

on:
  push:
    branches: [main]

env:
  HUSKY: 0
  VERSION: ${{ github.event.pull_request.number }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.yarn/cache
            ${{ github.workspace }}/.yarn/unplugged
            ${{ github.workspace }}/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      # Authenticate Google Cloud SDK
      - name: gcloud auth activate-service-account
        run: |
          echo "$GCP_SA_KEY" | base64 --decode > "$GOOGLE_APPLICATION_CREDENTIALS"
          gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"

      # Install dependencies
      - name: yarn install
        run: |
          yarn config set enableGlobalCache false
          yarn install

      # Build
      - run: yarn web:build
      - run: yarn api:build

      # Deploy
      # - run: yarn db:migrate --env=test
      # - run: yarn db:seed --env=test
      # - run: yarn api:deploy --env=test
      # - run: yarn web:deploy --env=test
